# Generated by Django 3.2.3 on 2022-01-02 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floversBackendApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Florist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='florist_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
