# Generated by Django 3.2.3 on 2022-01-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floversBackendApp', '0002_florist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bouquets', models.ManyToManyField(blank=True, related_name='sold_bouquets', to='floversBackendApp.Bouquet')),
                ('flowers', models.ManyToManyField(blank=True, related_name='sold_flowers', to='floversBackendApp.Flower')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('flowers', models.ManyToManyField(blank=True, related_name='delivery_flowers', to='floversBackendApp.Flower')),
            ],
        ),
        migrations.AddField(
            model_name='bouquet',
            name='flowers',
            field=models.ManyToManyField(blank=True, related_name='flowers_in_bouquet', to='floversBackendApp.Flower'),
        ),
        migrations.AddField(
            model_name='florist',
            name='bouquets',
            field=models.ManyToManyField(blank=True, related_name='bouquets_in_florist', to='floversBackendApp.Bouquet'),
        ),
        migrations.AddField(
            model_name='florist',
            name='deliveries',
            field=models.ManyToManyField(blank=True, related_name='deliveries_in_florist', to='floversBackendApp.Delivery'),
        ),
        migrations.AddField(
            model_name='florist',
            name='flowers',
            field=models.ManyToManyField(blank=True, related_name='flowers_in_florist', to='floversBackendApp.Flower'),
        ),
        migrations.AddField(
            model_name='florist',
            name='sales',
            field=models.ManyToManyField(blank=True, related_name='sales_in_florist', to='floversBackendApp.Sale'),
        ),
    ]
